import fs from 'fs';
import path from 'path';
import Papa from 'papaparse';
import { expectationEngine } from './expectation-engine.js';
import { realityEngine } from './reality-engine.js';
import { gapAnalyzer } from './gap-analyzer.js';
import dbConnect from '../db/connection.js';
import Report from '../db/Report.js';

export class Pipeline {
    constructor() {
        this.dataDir = path.join(process.cwd(), 'data');
        this.mockDir = path.join(this.dataDir, 'mock');
        this.processedDir = path.join(this.dataDir, 'processed');
    }

    async run() {
        console.log("🚀 Starting Veritas Finance Analysis Pipeline...");

        // Ensure output directory exists
        if (!fs.existsSync(this.processedDir)) {
            fs.mkdirSync(this.processedDir, { recursive: true });
        }

        // 1. EXTRACT PROMISES
        console.log("\n1️⃣  Running Expectation Engine...");
        const promises = await expectationEngine.batchExtract(path.join(this.mockDir, 'product_docs'));
        console.log(`   Found ${promises.length} product documents.`);

        // 2. ANALYZE REALITY (SENTIMENT)
        console.log("\n2️⃣  Running Reality Engine...");
        const reviewsPath = path.join(this.mockDir, 'customer_reviews.csv');
        let sentimentResults = [];

        if (fs.existsSync(reviewsPath)) {
            const csvContent = fs.readFileSync(reviewsPath, 'utf-8');
            const { data: reviews } = Papa.parse(csvContent, { header: true, skipEmptyLines: true });
            console.log(`   Parsed ${reviews.length} reviews.`);

            // Group reviews by product and analyze
            const products = [...new Set(reviews.map(r => r.product))];
            sentimentResults = products.map(p => realityEngine.analyzeProduct(reviews, p));
        } else {
            console.warn("   ⚠️ No reviews file found!");
        }

        // 3. DETECT GAPS
        console.log("\n3️⃣  Running Gap Analyzer...");
        const gapResults = [];

        promises.forEach(promise => {
            const sentiment = sentimentResults.find(s => s.product === promise.product_name) || {
                product: promise.product_name,
                dissatisfaction_index: 0,
                avg_sentiment: 0.5,
                top_complaints: []
            };

            const result = gapAnalyzer.analyze(promise, sentiment);
            gapResults.push(result);
        });

        console.log(`   Analyzed ${gapResults.length} products for mis-selling risks.`);

        // 4. SAVE RESULTS
        await this.saveRelationalData(gapResults);

        console.log("\n✅ Pipeline Complete! Results saved to data/processed/ and MongoDB");
        return gapResults;
    }

    async saveRelationalData(gapResults) {
        // 1. Save local JSON (Legacy/Backup)
        fs.writeFileSync(
            path.join(this.processedDir, 'analysis_results.json'),
            JSON.stringify(gapResults, null, 2)
        );

        // 2. Save CSV (Legacy/Export)
        const flatResults = gapResults.map(r => ({
            product: r.product_name,
            risk_level: r.risk_level,
            risk_score: r.overall_risk_score.toFixed(2),
            dissatisfaction: r.dissatisfaction_index.toFixed(1) + '%',
            mismatches_count: r.mismatches.length
        }));

        fs.writeFileSync(
            path.join(this.processedDir, 'summary_report.csv'),
            Papa.unparse(flatResults)
        );

        // 3. Save to MongoDB
        console.log("   💾 Saving to MongoDB...");
        try {
            await dbConnect();

            // Clear existing reports generated by pipeline to avoid duplicates if re-run
            // (Optional: depending on requirements. For now, let's upsert or just create new)
            // Strategy: Check if report exists for this product name and type 'Pipeline Analysis'

            for (const result of gapResults) {
                // Map the gap result to the Report schema
                const reportData = {
                    product_name: result.product_name,
                    issuer: result.issuer || 'Unknown Issuer',
                    risk_level: result.risk_level,
                    confidence: 100, // It's generated data
                    key_features: result.key_features || [],
                    promised_returns: result.promised_returns,
                    extracted_data: result, // Store full analysis
                    filename: `pipeline_analysis_${new Date().toISOString().split('T')[0]}.json`
                };

                // Use updateOne with upsert to prevent duplicates for the same product
                await Report.findOneAndUpdate(
                    { product_name: result.product_name },
                    reportData,
                    { upsert: true, new: true }
                );
            }
            console.log("      Successfully saved/updated reports in MongoDB.");

        } catch (error) {
            console.error("      ❌ Failed to save to MongoDB:", error);
            // Don't crash the pipeline, just log the error
        }
    }
}

export const pipeline = new Pipeline();
